language: nix
nix: 2.3.2
script: nix-shell --run 'make ci'
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist
  on:
    branch: master
