language: nix

nix: 2.3.2

script:
  - cachix use thought2
  - nix-env -iA cachix -f https://cachix.org/api/v1/install
  - export NIX_PATH=""; cachix push thought2 --watch-store & nix-build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: result
  on:
    branch: master
